# Generated by Django 4.2.1 on 2023-06-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0002_alter_categoria_fotografia_alter_producto_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fotografia',
            field=models.FileField(upload_to='estaticos/img/categorias'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fotografia',
            field=models.FileField(upload_to='estaticos/img/productos'),
        ),
    ]
