# Generated by Django 4.2.1 on 2023-06-04 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0005_alter_categoria_fotografia_alter_producto_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fotografia',
            field=models.FileField(upload_to='categorias'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fotografia',
            field=models.FileField(upload_to='productos'),
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('fotografia', models.FileField(upload_to='subcategorias')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.categoria', verbose_name='Categoría')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.subcategoria', verbose_name='Categoría'),
        ),
    ]
