# Generated by Django 4.2.1 on 2023-06-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0007_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.SmallIntegerField(default=0, verbose_name='Stock'),
        ),
    ]
