# Generated by Django 4.2.1 on 2023-06-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0008_producto_precio_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Precio'),
        ),
    ]
